name: Build and test the library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Compile Kotlin
      run: ./gradlew build

    - name: Convert models
      run: ./gradlew convertModels

    - name: Instal NPM dependencies
      run: npm ci

    - name: Build PEG Treebank parser
      run: npm run pegjs -- parser.pegjs

    - name: Test library
      run: npm test

    - name: Store built library
      uses: actions/upload-artifact@v2
      with:
        name: library
        path: |
          lib.js
          lib.d.ts
          build/js/packages/posTagger/kotlin/posTagger.js
          build/js/packages/posTagger/kotlin/posTagger.d.ts
          models/*.cbor.gz
          README.md
          LICENSE
          parser.js
          package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: NPM
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Download built library
        uses: actions/download-artifact@v2
        with:
          name: library

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v7.1.0
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
